# Generated by Django 4.2.8 on 2024-11-30 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("recordeddate", models.DateTimeField(blank=True, null=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("minutes", models.IntegerField(blank=True, null=True)),
                ("inserted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_activity",
                "managed": False,
            },
        ),
    ]
